version: "3"
services:
  # web:
  #   image: prefactor/gameoflife:v1
  #   command: flask run --host=0.0.0.0
  #   deploy:
  #     replicas: 4
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 50M
  #     restart_policy:
  #       condition: on-failure
  #   links: 
  #     - kafka
  #   ports:
  #     - "80:5000"
  #   networks:
  #     - webnet
  producer:
    image: prefactor/simpleproducer:v1
    links: 
      - kafka
  kafka:
    image: spotify/kafka
    ports: 
      - 9092:9092
      - 2181:2181
    hostname: kafka
    environment: 
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
      - TOPICS=gameoflife
  secor:
    image: ovotech/secor
    links: 
      - kafka
    env_file:
     - .env
networks:
  webnet: